# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  peer1.registry.node.connection:

networks:
  test:
    name: node_connection_network

services:
  peer1.registry.node.connection:
    container_name: peer1.registry.node.connection
    image: hyperledger/fabric-peer:latest
    restart: always
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=node_connection_network
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.registry.node.connection
      - CORE_PEER_ADDRESS=peer1.registry.node.connection:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.registry.node.connection:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.registry.node.connection:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.registry.node.connection:8051
      - CORE_PEER_LOCALMSPID=RegistryMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.registry.node.connection:18051
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1registry"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /home/seokwns/workspace/project/node-connection-backend/network/node-connection-network/compose/docker/peercfg:/etc/hyperledger/peercfg
      - /home/seokwns/workspace/project/node-connection-backend/network/node-connection-network/organizations/peerOrganizations/registry.node.connection/peers/peer1.registry.node.connection:/etc/hyperledger/fabric
      - peer1.registry.node.connection:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 8051:8051
      - 18051:18051
    networks:
      - test
